### ISSUE TITLE
md文档中带有url关键字时编译不过

### ISSUE THREAD

**Issue by supremeys** [teedoc/teedoc#3]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/teedoc/teedoc_main.py", line 1083, in generate
    raise e
  File "/usr/local/lib/python3.6/dist-packages/teedoc/teedoc_main.py", line 1065, in generate
    htmls_str = update_html_abs_path(htmls_str, site_root_url)
  File "/usr/local/lib/python3.6/dist-packages/teedoc/teedoc_main.py", line 827, in update_html_abs_path
    file_htmls[path] = re.sub(r'url(.*?)', re_del, file_htmls[path])
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.6/dist-packages/teedoc/teedoc_main.py", line 816, in re_del
    if content[4] != "/" and content[5] == "/" and content[6] != "/": # url("/static/...")
IndexError: string index out of range

**Comment by Neutree** [comment]
我在 md 中加了个 `url("/static/js/hello.jpg")`， 是可以通过的， 你先试试把软甲和插件都更新下， 最近更新比较频繁，刚刚还更新了个版本

```
pip install -U teedoc
teedoc install
```
