### ISSUE TITLE
错误Traceback (most recent call last):   File "/usr/local/bin/teedoc", line 8, in <module>     sys.exit(main())   File "/usr/local/lib/python3.10/dist-packages/teedoc/teedoc_main.py", line 2011, in main     module = __import__(plugin_import_name) ModuleNotFoundError: No module named 'teedoc_plugin_markdown_parser'

### ISSUE THREAD

**Issue by LCXlichengxuan** [teedoc/teedoc#32]
md文件写好后，使用`teedoc serve`或`teedoc build`运行时报错，提示：
```
Traceback (most recent call last):
  File "/usr/local/bin/teedoc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/teedoc/teedoc_main.py", line 2011, in main
    module = __import__(plugin_import_name)
ModuleNotFoundError: No module named 'teedoc_plugin_markdown_parser'
```
python和teedoc都已经全部更新，php版本8.0

**Comment by Neutree** [comment]
首先不需要php。。。 其次你要按照文档安装插件  在目录下面 teedoc install 一下
