### ISSUE TITLE
运行“teedoc serve”时报错

### ISSUE THREAD

**Issue by hehe210417** [teedoc/teedoc#33]
* Serving Flask app 'teedoc'
 * Debug mode: off
Exception in thread Thread-3 (files_watch):
Traceback (most recent call last):
  File "C:\Users\hehe210417\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\hehe210417\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hehe210417\AppData\Local\Programs\Python\Python311\Lib\site-packages\teedoc\teedoc_main.py", line 1785, in files_watch
    observer.schedule(handler, os.path.join(doc_src_path, name), True)
TypeError: BaseObserver.schedule() takes 3 positional arguments but 4 were given

**Comment by Neutree** [comment]
看起来像是`watchdog`这个模块版本问题，执行`pip install -U watchdog`更新一下这个模块试试

**Comment by hehe210417** [comment]
还是不行，watchdog目前最新是5.0.3，安装的时候就已经是了

**Comment by Neutree** [comment]
确实，那也算是一个小bug了，我修复一下兼容性

**Comment by Neutree** [comment]
已经修复，版本更新到了 1.37.5 版本
